name: cards

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: Edgible/card-kit
          path: .card-kit
      - run: .card-kit/run check-cards
